package deco

import "testing"

func TestAdminCloudMethods(t *testing.T) {
	testAdminMethodCases(t, []adminMethodCase{
		{
			name:      "AdminCloudAccountNotify",
			path:      "/admin/cloud",
			form:      "account",
			operation: "notify",
			call:      (*Client).AdminCloudAccountNotify,
		},
		{
			name:      "AdminCloudAccountWrite",
			path:      "/admin/cloud",
			form:      "account",
			operation: "write",
			call:      (*Client).AdminCloudAccountWrite,
		},
		{
			name:      "AdminCloudDDNSGet",
			path:      "/admin/cloud",
			form:      "ddns",
			operation: "get",
			call:      (*Client).AdminCloudDDNSGet,
		},
		{
			name:      "AdminCloudDDNSSet",
			path:      "/admin/cloud",
			form:      "ddns",
			operation: "set",
			call:      (*Client).AdminCloudDDNSSet,
		},
		{
			name:      "AdminCloudFirmwareDownload",
			path:      "/admin/cloud",
			form:      "firmware",
			operation: "download",
			call:      (*Client).AdminCloudFirmwareDownload,
		},
		{
			name:      "AdminCloudFirmwareSyncCheckFirmware",
			path:      "/admin/cloud",
			form:      "firmware",
			operation: "sync_check_firmware",
			call:      (*Client).AdminCloudFirmwareSyncCheckFirmware,
		},
		{
			name:      "AdminCloudFirmwareUpload",
			path:      "/admin/cloud",
			form:      "firmware",
			operation: "upload",
			call:      (*Client).AdminCloudFirmwareUpload,
		},
		{
			name:      "AdminCloudFirmwareStatusCheck",
			path:      "/admin/cloud",
			form:      "firmware_status",
			operation: "check",
			call:      (*Client).AdminCloudFirmwareStatusCheck,
		},
		{
			name:      "AdminCloudFirmwareStatusCheckUpgrade",
			path:      "/admin/cloud",
			form:      "firmware_status",
			operation: "check_upgrade",
			call:      (*Client).AdminCloudFirmwareStatusCheckUpgrade,
		},
		{
			name:      "AdminCloudFirmwareStatusLocalUpgrade",
			path:      "/admin/cloud",
			form:      "firmware_status",
			operation: "local_upgrade",
			call:      (*Client).AdminCloudFirmwareStatusLocalUpgrade,
		},
		{
			name:      "AdminCloudFirmwareStatusRead",
			path:      "/admin/cloud",
			form:      "firmware_status",
			operation: "read",
			call:      (*Client).AdminCloudFirmwareStatusRead,
		},
		{
			name:      "AdminCloudFirmwareStatusUpgrade",
			path:      "/admin/cloud",
			form:      "firmware_status",
			operation: "upgrade",
			call:      (*Client).AdminCloudFirmwareStatusUpgrade,
		},
		{
			name:      "AdminCloudGroupAdd",
			path:      "/admin/cloud",
			form:      "group",
			operation: "add",
			call:      (*Client).AdminCloudGroupAdd,
		},
		{
			name:      "AdminCloudGroupCreate",
			path:      "/admin/cloud",
			form:      "group",
			operation: "create",
			call:      (*Client).AdminCloudGroupCreate,
		},
		{
			name:      "AdminCloudManagerGet",
			path:      "/admin/cloud",
			form:      "manager",
			operation: "get",
			call:      (*Client).AdminCloudManagerGet,
		},
		{
			name:      "AdminCloudManagerSet",
			path:      "/admin/cloud",
			form:      "manager",
			operation: "set",
			call:      (*Client).AdminCloudManagerSet,
		},
		{
			name:      "AdminCloudMessageGet",
			path:      "/admin/cloud",
			form:      "message",
			operation: "get",
			call:      (*Client).AdminCloudMessageGet,
		},
		{
			name:      "AdminCloudMessageIoTRead",
			path:      "/admin/cloud",
			form:      "message",
			operation: "iot_read",
			call:      (*Client).AdminCloudMessageIoTRead,
		},
		{
			name:      "AdminCloudMessagePush",
			path:      "/admin/cloud",
			form:      "message",
			operation: "push",
			call:      (*Client).AdminCloudMessagePush,
		},
		{
			name:      "AdminCloudMessageRead",
			path:      "/admin/cloud",
			form:      "message",
			operation: "read",
			call:      (*Client).AdminCloudMessageRead,
		},
		{
			name:      "AdminCloudMessageRemove",
			path:      "/admin/cloud",
			form:      "message",
			operation: "remove",
			call:      (*Client).AdminCloudMessageRemove,
		},
		{
			name:      "AdminCloudMessageReport",
			path:      "/admin/cloud",
			form:      "message",
			operation: "report",
			call:      (*Client).AdminCloudMessageReport,
		},
		{
			name:      "AdminCloudMessageSet",
			path:      "/admin/cloud",
			form:      "message",
			operation: "set",
			call:      (*Client).AdminCloudMessageSet,
		},
		{
			name:      "AdminCloudMessageUpdate",
			path:      "/admin/cloud",
			form:      "message",
			operation: "update",
			call:      (*Client).AdminCloudMessageUpdate,
		},
		{
			name:      "AdminCloudMiniFirmwareCheck",
			path:      "/admin/cloud",
			form:      "mini_firmware",
			operation: "check",
			call:      (*Client).AdminCloudMiniFirmwareCheck,
		},
		{
			name:      "AdminCloudMiniFirmwareCheckUpgrade",
			path:      "/admin/cloud",
			form:      "mini_firmware",
			operation: "check_upgrade",
			call:      (*Client).AdminCloudMiniFirmwareCheckUpgrade,
		},
		{
			name:      "AdminCloudMiniFirmwareDownload",
			path:      "/admin/cloud",
			form:      "mini_firmware",
			operation: "download",
			call:      (*Client).AdminCloudMiniFirmwareDownload,
		},
		{
			name:      "AdminCloudMiniFirmwareLocalUpgrade",
			path:      "/admin/cloud",
			form:      "mini_firmware",
			operation: "local_upgrade",
			call:      (*Client).AdminCloudMiniFirmwareLocalUpgrade,
		},
		{
			name:      "AdminCloudMiniFirmwareRead",
			path:      "/admin/cloud",
			form:      "mini_firmware",
			operation: "read",
			call:      (*Client).AdminCloudMiniFirmwareRead,
		},
		{
			name:      "AdminCloudMiniFirmwareUpgrade",
			path:      "/admin/cloud",
			form:      "mini_firmware",
			operation: "upgrade",
			call:      (*Client).AdminCloudMiniFirmwareUpgrade,
		},
		{
			name:      "AdminCloudMiniFirmwareUpload",
			path:      "/admin/cloud",
			form:      "mini_firmware",
			operation: "upload",
			call:      (*Client).AdminCloudMiniFirmwareUpload,
		},
		{
			name:      "AdminCloudNicknameRead",
			path:      "/admin/cloud",
			form:      "nickname",
			operation: "read",
			call:      (*Client).AdminCloudNicknameRead,
		},
		{
			name:      "AdminCloudNicknameWrite",
			path:      "/admin/cloud",
			form:      "nickname",
			operation: "write",
			call:      (*Client).AdminCloudNicknameWrite,
		},
		{
			name:      "AdminCloudProxyWrite",
			path:      "/admin/cloud",
			form:      "proxy",
			operation: "write",
			call:      (*Client).AdminCloudProxyWrite,
		},
		{
			name:      "AdminCloudSystemBind",
			path:      "/admin/cloud",
			form:      "system",
			operation: "bind",
			call:      (*Client).AdminCloudSystemBind,
		},
		{
			name:      "AdminCloudSystemRemove",
			path:      "/admin/cloud",
			form:      "system",
			operation: "remove",
			call:      (*Client).AdminCloudSystemRemove,
		},
		{
			name:      "AdminCloudSystemRemoveAll",
			path:      "/admin/cloud",
			form:      "system",
			operation: "remove_all",
			call:      (*Client).AdminCloudSystemRemoveAll,
		},
		{
			name:      "AdminCloudSystemUnbind",
			path:      "/admin/cloud",
			form:      "system",
			operation: "unbind",
			call:      (*Client).AdminCloudSystemUnbind,
		},
	})
}
