package deco

import "testing"

func TestAdminMobileAppMethods(t *testing.T) {
	testAdminMethodCases(t, []adminMethodCase{
		{
			name:      "AdminMobileAppAutoTestAllInfoRead",
			path:      "/admin/mobile_app/auto_test",
			form:      "all_info",
			operation: "read",
			call:      (*Client).AdminMobileAppAutoTestAllInfoRead,
		},
		{
			name:      "AdminMobileAppAutoTestDHCPRead",
			path:      "/admin/mobile_app/auto_test",
			form:      "dhcp",
			operation: "read",
			call:      (*Client).AdminMobileAppAutoTestDHCPRead,
		},
		{
			name:      "AdminMobileAppAutoTestNATRead",
			path:      "/admin/mobile_app/auto_test",
			form:      "nat",
			operation: "read",
			call:      (*Client).AdminMobileAppAutoTestNATRead,
		},
		{
			name:      "AdminMobileAppAutoTestTestRead",
			path:      "/admin/mobile_app/auto_test",
			form:      "test",
			operation: "read",
			call:      (*Client).AdminMobileAppAutoTestTestRead,
		},
		{
			name:      "AdminMobileAppAutoTestUPnPList",
			path:      "/admin/mobile_app/auto_test",
			form:      "upnp",
			operation: "list",
			call:      (*Client).AdminMobileAppAutoTestUPnPList,
		},
		{
			name:      "AdminMobileAppAutoTestUPnPRead",
			path:      "/admin/mobile_app/auto_test",
			form:      "upnp",
			operation: "read",
			call:      (*Client).AdminMobileAppAutoTestUPnPRead,
		},
		{
			name:      "AdminMobileAppAutoTestWiFiRead",
			path:      "/admin/mobile_app/auto_test",
			form:      "wifi",
			operation: "read",
			call:      (*Client).AdminMobileAppAutoTestWiFiRead,
		},
		{
			name:      "AdminMobileAppClientAddrReservationAdd",
			path:      "/admin/mobile_app/client",
			form:      "addr_reservation",
			operation: "add",
			call:      (*Client).AdminMobileAppClientAddrReservationAdd,
		},
		{
			name:      "AdminMobileAppClientAddrReservationGetlist",
			path:      "/admin/mobile_app/client",
			form:      "addr_reservation",
			operation: "getlist",
			call:      (*Client).AdminMobileAppClientAddrReservationGetlist,
		},
		{
			name:      "AdminMobileAppClientAddrReservationModify",
			path:      "/admin/mobile_app/client",
			form:      "addr_reservation",
			operation: "modify",
			call:      (*Client).AdminMobileAppClientAddrReservationModify,
		},
		{
			name:      "AdminMobileAppClientAddrReservationRemove",
			path:      "/admin/mobile_app/client",
			form:      "addr_reservation",
			operation: "remove",
			call:      (*Client).AdminMobileAppClientAddrReservationRemove,
		},
		{
			name:      "AdminMobileAppClientBlackListBlock",
			path:      "/admin/mobile_app/client",
			form:      "black_list",
			operation: "block",
			call:      (*Client).AdminMobileAppClientBlackListBlock,
		},
		{
			name:      "AdminMobileAppClientBlackListList",
			path:      "/admin/mobile_app/client",
			form:      "black_list",
			operation: "list",
			call:      (*Client).AdminMobileAppClientBlackListList,
		},
		{
			name:      "AdminMobileAppClientBlackListModify",
			path:      "/admin/mobile_app/client",
			form:      "black_list",
			operation: "modify",
			call:      (*Client).AdminMobileAppClientBlackListModify,
		},
		{
			name:      "AdminMobileAppClientBlackListUnblock",
			path:      "/admin/mobile_app/client",
			form:      "black_list",
			operation: "unblock",
			call:      (*Client).AdminMobileAppClientBlackListUnblock,
		},
		{
			name:      "AdminMobileAppClientClientAccessRead",
			path:      "/admin/mobile_app/client",
			form:      "client_access",
			operation: "read",
			call:      (*Client).AdminMobileAppClientClientAccessRead,
		},
		{
			name:      "AdminMobileAppClientClientAccessWrite",
			path:      "/admin/mobile_app/client",
			form:      "client_access",
			operation: "write",
			call:      (*Client).AdminMobileAppClientClientAccessWrite,
		},
		{
			name:      "AdminMobileAppClientClientIsolationRead",
			path:      "/admin/mobile_app/client",
			form:      "client_isolation",
			operation: "read",
			call:      (*Client).AdminMobileAppClientClientIsolationRead,
		},
		{
			name:      "AdminMobileAppClientClientIsolationWrite",
			path:      "/admin/mobile_app/client",
			form:      "client_isolation",
			operation: "write",
			call:      (*Client).AdminMobileAppClientClientIsolationWrite,
		},
		{
			name:      "AdminMobileAppClientClientListRead",
			path:      "/admin/mobile_app/client",
			form:      "client_list",
			operation: "read",
			call:      (*Client).AdminMobileAppClientClientListRead,
		},
		{
			name:      "AdminMobileAppClientClientListRemove",
			path:      "/admin/mobile_app/client",
			form:      "client_list",
			operation: "remove",
			call:      (*Client).AdminMobileAppClientClientListRemove,
		},
		{
			name:      "AdminMobileAppClientClientListWrite",
			path:      "/admin/mobile_app/client",
			form:      "client_list",
			operation: "write",
			call:      (*Client).AdminMobileAppClientClientListWrite,
		},
		{
			name:      "AdminMobileAppClientLeaseGet",
			path:      "/admin/mobile_app/client",
			form:      "lease",
			operation: "get",
			call:      (*Client).AdminMobileAppClientLeaseGet,
		},
		{
			name:      "AdminMobileAppClientTrafficStatClient",
			path:      "/admin/mobile_app/client",
			form:      "traffic_stat",
			operation: "client",
			call:      (*Client).AdminMobileAppClientTrafficStatClient,
		},
		{
			name:      "AdminMobileAppClientTrafficStatList",
			path:      "/admin/mobile_app/client",
			form:      "traffic_stat",
			operation: "list",
			call:      (*Client).AdminMobileAppClientTrafficStatList,
		},
		{
			name:      "AdminMobileAppCloudAccountNotify",
			path:      "/admin/mobile_app/cloud",
			form:      "account",
			operation: "notify",
			call:      (*Client).AdminMobileAppCloudAccountNotify,
		},
		{
			name:      "AdminMobileAppCloudAccountSync",
			path:      "/admin/mobile_app/cloud",
			form:      "account",
			operation: "sync",
			call:      (*Client).AdminMobileAppCloudAccountSync,
		},
		{
			name:      "AdminMobileAppCloudAccountTransfer",
			path:      "/admin/mobile_app/cloud",
			form:      "account",
			operation: "transfer",
			call:      (*Client).AdminMobileAppCloudAccountTransfer,
		},
		{
			name:      "AdminMobileAppCloudAccountWrite",
			path:      "/admin/mobile_app/cloud",
			form:      "account",
			operation: "write",
			call:      (*Client).AdminMobileAppCloudAccountWrite,
		},
		{
			name:      "AdminMobileAppCloudAutoUpgradeRead",
			path:      "/admin/mobile_app/cloud",
			form:      "auto_upgrade",
			operation: "read",
			call:      (*Client).AdminMobileAppCloudAutoUpgradeRead,
		},
		{
			name:      "AdminMobileAppCloudAutoUpgradeWrite",
			path:      "/admin/mobile_app/cloud",
			form:      "auto_upgrade",
			operation: "write",
			call:      (*Client).AdminMobileAppCloudAutoUpgradeWrite,
		},
		{
			name:      "AdminMobileAppCloudDDNSGet",
			path:      "/admin/mobile_app/cloud",
			form:      "ddns",
			operation: "get",
			call:      (*Client).AdminMobileAppCloudDDNSGet,
		},
		{
			name:      "AdminMobileAppCloudDDNSSet",
			path:      "/admin/mobile_app/cloud",
			form:      "ddns",
			operation: "set",
			call:      (*Client).AdminMobileAppCloudDDNSSet,
		},
		{
			name:      "AdminMobileAppCloudFirmwareCheck",
			path:      "/admin/mobile_app/cloud",
			form:      "firmware",
			operation: "check",
			call:      (*Client).AdminMobileAppCloudFirmwareCheck,
		},
		{
			name:      "AdminMobileAppCloudFirmwareDownload",
			path:      "/admin/mobile_app/cloud",
			form:      "firmware",
			operation: "download",
			call:      (*Client).AdminMobileAppCloudFirmwareDownload,
		},
		{
			name:      "AdminMobileAppCloudFirmwareGetSync",
			path:      "/admin/mobile_app/cloud",
			form:      "firmware",
			operation: "get_sync",
			call:      (*Client).AdminMobileAppCloudFirmwareGetSync,
		},
		{
			name:      "AdminMobileAppCloudFirmwareRead",
			path:      "/admin/mobile_app/cloud",
			form:      "firmware",
			operation: "read",
			call:      (*Client).AdminMobileAppCloudFirmwareRead,
		},
		{
			name:      "AdminMobileAppCloudFirmwareSyncCheckFirmware",
			path:      "/admin/mobile_app/cloud",
			form:      "firmware",
			operation: "sync_check_firmware",
			call:      (*Client).AdminMobileAppCloudFirmwareSyncCheckFirmware,
		},
		{
			name:      "AdminMobileAppCloudFirmwareUpgrade",
			path:      "/admin/mobile_app/cloud",
			form:      "firmware",
			operation: "upgrade",
			call:      (*Client).AdminMobileAppCloudFirmwareUpgrade,
		},
		{
			name:      "AdminMobileAppCloudGroupAdd",
			path:      "/admin/mobile_app/cloud",
			form:      "group",
			operation: "add",
			call:      (*Client).AdminMobileAppCloudGroupAdd,
		},
		{
			name:      "AdminMobileAppCloudGroupCreate",
			path:      "/admin/mobile_app/cloud",
			form:      "group",
			operation: "create",
			call:      (*Client).AdminMobileAppCloudGroupCreate,
		},
		{
			name:      "AdminMobileAppCloudHomecareServiceGet",
			path:      "/admin/mobile_app/cloud",
			form:      "homecare_service",
			operation: "get",
			call:      (*Client).AdminMobileAppCloudHomecareServiceGet,
		},
		{
			name:      "AdminMobileAppCloudManagerGet",
			path:      "/admin/mobile_app/cloud",
			form:      "manager",
			operation: "get",
			call:      (*Client).AdminMobileAppCloudManagerGet,
		},
		{
			name:      "AdminMobileAppCloudManagerSet",
			path:      "/admin/mobile_app/cloud",
			form:      "manager",
			operation: "set",
			call:      (*Client).AdminMobileAppCloudManagerSet,
		},
		{
			name:      "AdminMobileAppCloudMessageGet",
			path:      "/admin/mobile_app/cloud",
			form:      "message",
			operation: "get",
			call:      (*Client).AdminMobileAppCloudMessageGet,
		},
		{
			name:      "AdminMobileAppCloudMessageIoTRead",
			path:      "/admin/mobile_app/cloud",
			form:      "message",
			operation: "iot_read",
			call:      (*Client).AdminMobileAppCloudMessageIoTRead,
		},
		{
			name:      "AdminMobileAppCloudMessagePush",
			path:      "/admin/mobile_app/cloud",
			form:      "message",
			operation: "push",
			call:      (*Client).AdminMobileAppCloudMessagePush,
		},
		{
			name:      "AdminMobileAppCloudMessagePushWeekly",
			path:      "/admin/mobile_app/cloud",
			form:      "message",
			operation: "push_weekly",
			call:      (*Client).AdminMobileAppCloudMessagePushWeekly,
		},
		{
			name:      "AdminMobileAppCloudMessageRead",
			path:      "/admin/mobile_app/cloud",
			form:      "message",
			operation: "read",
			call:      (*Client).AdminMobileAppCloudMessageRead,
		},
		{
			name:      "AdminMobileAppCloudMessageRemove",
			path:      "/admin/mobile_app/cloud",
			form:      "message",
			operation: "remove",
			call:      (*Client).AdminMobileAppCloudMessageRemove,
		},
		{
			name:      "AdminMobileAppCloudMessageReport",
			path:      "/admin/mobile_app/cloud",
			form:      "message",
			operation: "report",
			call:      (*Client).AdminMobileAppCloudMessageReport,
		},
		{
			name:      "AdminMobileAppCloudMessageSet",
			path:      "/admin/mobile_app/cloud",
			form:      "message",
			operation: "set",
			call:      (*Client).AdminMobileAppCloudMessageSet,
		},
		{
			name:      "AdminMobileAppCloudMessageUpdate",
			path:      "/admin/mobile_app/cloud",
			form:      "message",
			operation: "update",
			call:      (*Client).AdminMobileAppCloudMessageUpdate,
		},
		{
			name:      "AdminMobileAppCloudNicknameRead",
			path:      "/admin/mobile_app/cloud",
			form:      "nickname",
			operation: "read",
			call:      (*Client).AdminMobileAppCloudNicknameRead,
		},
		{
			name:      "AdminMobileAppCloudNicknameWrite",
			path:      "/admin/mobile_app/cloud",
			form:      "nickname",
			operation: "write",
			call:      (*Client).AdminMobileAppCloudNicknameWrite,
		},
		{
			name:      "AdminMobileAppCloudProxyWrite",
			path:      "/admin/mobile_app/cloud",
			form:      "proxy",
			operation: "write",
			call:      (*Client).AdminMobileAppCloudProxyWrite,
		},
		{
			name:      "AdminMobileAppCloudSystemBind",
			path:      "/admin/mobile_app/cloud",
			form:      "system",
			operation: "bind",
			call:      (*Client).AdminMobileAppCloudSystemBind,
		},
		{
			name:      "AdminMobileAppCloudSystemRemove",
			path:      "/admin/mobile_app/cloud",
			form:      "system",
			operation: "remove",
			call:      (*Client).AdminMobileAppCloudSystemRemove,
		},
		{
			name:      "AdminMobileAppCloudSystemRemoveAll",
			path:      "/admin/mobile_app/cloud",
			form:      "system",
			operation: "remove_all",
			call:      (*Client).AdminMobileAppCloudSystemRemoveAll,
		},
		{
			name:      "AdminMobileAppCloudSystemUnbind",
			path:      "/admin/mobile_app/cloud",
			form:      "system",
			operation: "unbind",
			call:      (*Client).AdminMobileAppCloudSystemUnbind,
		},
		{
			name:      "AdminMobileAppComponentListBluetoothRead",
			path:      "/admin/mobile_app/component_list",
			form:      "bluetooth",
			operation: "read",
			call:      (*Client).AdminMobileAppComponentListBluetoothRead,
		},
		{
			name:      "AdminMobileAppComponentListMobileRead",
			path:      "/admin/mobile_app/component_list",
			form:      "mobile",
			operation: "read",
			call:      (*Client).AdminMobileAppComponentListMobileRead,
		},
		{
			name:      "AdminMobileAppComponentListProfileRead",
			path:      "/admin/mobile_app/component_list",
			form:      "profile",
			operation: "read",
			call:      (*Client).AdminMobileAppComponentListProfileRead,
		},
		{
			name:      "AdminMobileAppCWMPCWMPGet",
			path:      "/admin/mobile_app/cwmp",
			form:      "cwmp",
			operation: "get",
			call:      (*Client).AdminMobileAppCWMPCWMPGet,
		},
		{
			name:      "AdminMobileAppCWMPCWMPSet",
			path:      "/admin/mobile_app/cwmp",
			form:      "cwmp",
			operation: "set",
			call:      (*Client).AdminMobileAppCWMPCWMPSet,
		},
		{
			name:      "AdminMobileAppDDNSDDNSGet",
			path:      "/admin/mobile_app/ddns",
			form:      "ddns",
			operation: "get",
			call:      (*Client).AdminMobileAppDDNSDDNSGet,
		},
		{
			name:      "AdminMobileAppDDNSDDNSSet",
			path:      "/admin/mobile_app/ddns",
			form:      "ddns",
			operation: "set",
			call:      (*Client).AdminMobileAppDDNSDDNSSet,
		},
		{
			name:      "AdminMobileAppDebugQLogStart",
			path:      "/admin/mobile_app/debug",
			form:      "qlog",
			operation: "start",
			call:      (*Client).AdminMobileAppDebugQLogStart,
		},
		{
			name:      "AdminMobileAppDebugQLogStop",
			path:      "/admin/mobile_app/debug",
			form:      "qlog",
			operation: "stop",
			call:      (*Client).AdminMobileAppDebugQLogStop,
		},
		{
			name:      "AdminMobileAppDebugSimplecomStart",
			path:      "/admin/mobile_app/debug",
			form:      "simplecom",
			operation: "start",
			call:      (*Client).AdminMobileAppDebugSimplecomStart,
		},
		{
			name:      "AdminMobileAppDebugSimplecomStop",
			path:      "/admin/mobile_app/debug",
			form:      "simplecom",
			operation: "stop",
			call:      (*Client).AdminMobileAppDebugSimplecomStop,
		},
		{
			name:      "AdminMobileAppDebugTMStart",
			path:      "/admin/mobile_app/debug",
			form:      "tm",
			operation: "start",
			call:      (*Client).AdminMobileAppDebugTMStart,
		},
		{
			name:      "AdminMobileAppDebugTMStop",
			path:      "/admin/mobile_app/debug",
			form:      "tm",
			operation: "stop",
			call:      (*Client).AdminMobileAppDebugTMStop,
		},
		{
			name:      "AdminMobileAppDebugTty2tcpStart",
			path:      "/admin/mobile_app/debug",
			form:      "tty2tcp",
			operation: "start",
			call:      (*Client).AdminMobileAppDebugTty2tcpStart,
		},
		{
			name:      "AdminMobileAppDebugTty2tcpStop",
			path:      "/admin/mobile_app/debug",
			form:      "tty2tcp",
			operation: "stop",
			call:      (*Client).AdminMobileAppDebugTty2tcpStop,
		},
		{
			name:      "AdminMobileAppDeviceAlertOperationModeSwitchSet",
			path:      "/admin/mobile_app/device",
			form:      "alert_operation_mode_switch",
			operation: "set",
			call:      (*Client).AdminMobileAppDeviceAlertOperationModeSwitchSet,
		},
		{
			name:      "AdminMobileAppDeviceDetectModeRead",
			path:      "/admin/mobile_app/device",
			form:      "detect_mode",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceDetectModeRead,
		},
		{
			name:      "AdminMobileAppDeviceDetectModeWrite",
			path:      "/admin/mobile_app/device",
			form:      "detect_mode",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceDetectModeWrite,
		},
		{
			name:      "AdminMobileAppDeviceDeviceListRead",
			path:      "/admin/mobile_app/device",
			form:      "device_list",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceDeviceListRead,
		},
		{
			name:      "AdminMobileAppDeviceDeviceListRemove",
			path:      "/admin/mobile_app/device",
			form:      "device_list",
			operation: "remove",
			call:      (*Client).AdminMobileAppDeviceDeviceListRemove,
		},
		{
			name:      "AdminMobileAppDeviceDevicePreferSetSet",
			path:      "/admin/mobile_app/device",
			form:      "device_prefer_set",
			operation: "set",
			call:      (*Client).AdminMobileAppDeviceDevicePreferSetSet,
		},
		{
			name:      "AdminMobileAppDeviceEcoModeRead",
			path:      "/admin/mobile_app/device",
			form:      "eco_mode",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceEcoModeRead,
		},
		{
			name:      "AdminMobileAppDeviceEcoModeWrite",
			path:      "/admin/mobile_app/device",
			form:      "eco_mode",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceEcoModeWrite,
		},
		{
			name:      "AdminMobileAppDeviceEnvarWrite",
			path:      "/admin/mobile_app/device",
			form:      "envar",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceEnvarWrite,
		},
		{
			name:      "AdminMobileAppDeviceFixedWANPortGet",
			path:      "/admin/mobile_app/device",
			form:      "fixed_wan_port",
			operation: "get",
			call:      (*Client).AdminMobileAppDeviceFixedWANPortGet,
		},
		{
			name:      "AdminMobileAppDeviceFixedWANPortSet",
			path:      "/admin/mobile_app/device",
			form:      "fixed_wan_port",
			operation: "set",
			call:      (*Client).AdminMobileAppDeviceFixedWANPortSet,
		},
		{
			name:      "AdminMobileAppDeviceLEDRead",
			path:      "/admin/mobile_app/device",
			form:      "led",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceLEDRead,
		},
		{
			name:      "AdminMobileAppDeviceLEDWrite",
			path:      "/admin/mobile_app/device",
			form:      "led",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceLEDWrite,
		},
		{
			name:      "AdminMobileAppDeviceRebootRead",
			path:      "/admin/mobile_app/device",
			form:      "reboot",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceRebootRead,
		},
		{
			name:      "AdminMobileAppDeviceRebootWrite",
			path:      "/admin/mobile_app/device",
			form:      "reboot",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceRebootWrite,
		},
		{
			name:      "AdminMobileAppDeviceSignalLevelListGet",
			path:      "/admin/mobile_app/device",
			form:      "signal_level_list",
			operation: "get",
			call:      (*Client).AdminMobileAppDeviceSignalLevelListGet,
		},
		{
			name:      "AdminMobileAppDeviceSpeedinfoRead",
			path:      "/admin/mobile_app/device",
			form:      "speedinfo",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceSpeedinfoRead,
		},
		{
			name:      "AdminMobileAppDeviceSpeedtestClear",
			path:      "/admin/mobile_app/device",
			form:      "speedtest",
			operation: "clear",
			call:      (*Client).AdminMobileAppDeviceSpeedtestClear,
		},
		{
			name:      "AdminMobileAppDeviceSpeedtestGet",
			path:      "/admin/mobile_app/device",
			form:      "speedtest",
			operation: "get",
			call:      (*Client).AdminMobileAppDeviceSpeedtestGet,
		},
		{
			name:      "AdminMobileAppDeviceSpeedtestGetServer",
			path:      "/admin/mobile_app/device",
			form:      "speedtest",
			operation: "get_server",
			call:      (*Client).AdminMobileAppDeviceSpeedtestGetServer,
		},
		{
			name:      "AdminMobileAppDeviceSpeedtestRead",
			path:      "/admin/mobile_app/device",
			form:      "speedtest",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceSpeedtestRead,
		},
		{
			name:      "AdminMobileAppDeviceSpeedtestStop",
			path:      "/admin/mobile_app/device",
			form:      "speedtest",
			operation: "stop",
			call:      (*Client).AdminMobileAppDeviceSpeedtestStop,
		},
		{
			name:      "AdminMobileAppDeviceSpeedtestWrite",
			path:      "/admin/mobile_app/device",
			form:      "speedtest",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceSpeedtestWrite,
		},
		{
			name:      "AdminMobileAppDeviceSyncRead",
			path:      "/admin/mobile_app/device",
			form:      "sync",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceSyncRead,
		},
		{
			name:      "AdminMobileAppDeviceSyncWrite",
			path:      "/admin/mobile_app/device",
			form:      "sync",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceSyncWrite,
		},
		{
			name:      "AdminMobileAppDeviceSysmodeRead",
			path:      "/admin/mobile_app/device",
			form:      "sysmode",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceSysmodeRead,
		},
		{
			name:      "AdminMobileAppDeviceSysmodeSetBackup",
			path:      "/admin/mobile_app/device",
			form:      "sysmode",
			operation: "set_backup",
			call:      (*Client).AdminMobileAppDeviceSysmodeSetBackup,
		},
		{
			name:      "AdminMobileAppDeviceSysmodeWrite",
			path:      "/admin/mobile_app/device",
			form:      "sysmode",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceSysmodeWrite,
		},
		{
			name:      "AdminMobileAppDeviceSystemFactory",
			path:      "/admin/mobile_app/device",
			form:      "system",
			operation: "factory",
			call:      (*Client).AdminMobileAppDeviceSystemFactory,
		},
		{
			name:      "AdminMobileAppDeviceSystemGateway",
			path:      "/admin/mobile_app/device",
			form:      "system",
			operation: "gateway",
			call:      (*Client).AdminMobileAppDeviceSystemGateway,
		},
		{
			name:      "AdminMobileAppDeviceSystemReboot",
			path:      "/admin/mobile_app/device",
			form:      "system",
			operation: "reboot",
			call:      (*Client).AdminMobileAppDeviceSystemReboot,
		},
		{
			name:      "AdminMobileAppDeviceSystimeRead",
			path:      "/admin/mobile_app/device",
			form:      "systime",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceSystimeRead,
		},
		{
			name:      "AdminMobileAppDeviceSystimeWrite",
			path:      "/admin/mobile_app/device",
			form:      "systime",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceSystimeWrite,
		},
		{
			name:      "AdminMobileAppDeviceTimesettingRead",
			path:      "/admin/mobile_app/device",
			form:      "timesetting",
			operation: "read",
			call:      (*Client).AdminMobileAppDeviceTimesettingRead,
		},
		{
			name:      "AdminMobileAppDeviceTimesettingWrite",
			path:      "/admin/mobile_app/device",
			form:      "timesetting",
			operation: "write",
			call:      (*Client).AdminMobileAppDeviceTimesettingWrite,
		},
		{
			name:      "AdminMobileAppDHCPDHCPAPRead",
			path:      "/admin/mobile_app/dhcp",
			form:      "dhcp_ap",
			operation: "read",
			call:      (*Client).AdminMobileAppDHCPDHCPAPRead,
		},
		{
			name:      "AdminMobileAppDHCPDHCPAPWrite",
			path:      "/admin/mobile_app/dhcp",
			form:      "dhcp_ap",
			operation: "write",
			call:      (*Client).AdminMobileAppDHCPDHCPAPWrite,
		},
		{
			name:      "AdminMobileAppDHCPDHCPDialWrite",
			path:      "/admin/mobile_app/dhcp",
			form:      "dhcp_dial",
			operation: "write",
			call:      (*Client).AdminMobileAppDHCPDHCPDialWrite,
		},
		{
			name:      "AdminMobileAppDHCPDHCPInfoRead",
			path:      "/admin/mobile_app/dhcp",
			form:      "dhcp_info",
			operation: "read",
			call:      (*Client).AdminMobileAppDHCPDHCPInfoRead,
		},
		{
			name:      "AdminMobileAppDHCPDHCPInfoWrite",
			path:      "/admin/mobile_app/dhcp",
			form:      "dhcp_info",
			operation: "write",
			call:      (*Client).AdminMobileAppDHCPDHCPInfoWrite,
		},
		{
			name:      "AdminMobileAppGAInfoHWVerRead",
			path:      "/admin/mobile_app/ga_info",
			form:      "hw_ver",
			operation: "read",
			call:      (*Client).AdminMobileAppGAInfoHWVerRead,
		},
		{
			name:      "AdminMobileAppGAInfoHWVerWrite",
			path:      "/admin/mobile_app/ga_info",
			form:      "hw_ver",
			operation: "write",
			call:      (*Client).AdminMobileAppGAInfoHWVerWrite,
		},
		{
			name:      "AdminMobileAppGAInfoStatusGet",
			path:      "/admin/mobile_app/ga_info",
			form:      "status",
			operation: "get",
			call:      (*Client).AdminMobileAppGAInfoStatusGet,
		},
		{
			name:      "AdminMobileAppGAInfoStatusGetInternal",
			path:      "/admin/mobile_app/ga_info",
			form:      "status",
			operation: "get_internal",
			call:      (*Client).AdminMobileAppGAInfoStatusGetInternal,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationAddAction",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "add_action",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationAddAction,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationAddTask",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "add_task",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationAddTask,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationAddTrigger",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "add_trigger",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationAddTrigger,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationGetHistory",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "get_history",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationGetHistory,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationGetTasklist",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "get_tasklist",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationGetTasklist,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationModifyAction",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "modify_action",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationModifyAction,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationModifyTask",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "modify_task",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationModifyTask,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationModifyTaskList",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "modify_task_list",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationModifyTaskList,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationModifyTrigger",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "modify_trigger",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationModifyTrigger,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationRemoveActionlist",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "remove_actionlist",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationRemoveActionlist,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationRemoveHistory",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "remove_history",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationRemoveHistory,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationRemoveTasklist",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "remove_tasklist",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationRemoveTasklist,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotautomationRemoveTriggerlist",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotautomation",
			operation: "remove_triggerlist",
			call:      (*Client).AdminMobileAppIoTAutomationIotautomationRemoveTriggerlist,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickAddAction",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "add_action",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickAddAction,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickAddScene",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "add_scene",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickAddScene,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickGetHistory",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "get_history",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickGetHistory,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickGetlist",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "getlist",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickGetlist,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickModifyAction",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "modify_action",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickModifyAction,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickModifyScene",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "modify_scene",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickModifyScene,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickRemoveActionlist",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "remove_actionlist",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickRemoveActionlist,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickRemoveHistory",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "remove_history",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickRemoveHistory,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickRemoveScene",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "remove_scene",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickRemoveScene,
		},
		{
			name:      "AdminMobileAppIoTAutomationIotoneclickSet",
			path:      "/admin/mobile_app/iot_automation",
			form:      "iotoneclick",
			operation: "set",
			call:      (*Client).AdminMobileAppIoTAutomationIotoneclickSet,
		},
		{
			name:      "AdminMobileAppIoTClientMeshClientMeshSet",
			path:      "/admin/mobile_app/iot_client_mesh",
			form:      "client_mesh",
			operation: "set",
			call:      (*Client).AdminMobileAppIoTClientMeshClientMeshSet,
		},
		{
			name:      "AdminMobileAppIoTCloudIoTCloudReq",
			path:      "/admin/mobile_app/iot_cloud",
			form:      "",
			operation: "iot_cloud_req",
			call:      (*Client).AdminMobileAppIoTCloudIoTCloudReq,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceAdd",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "add",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceAdd,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceBeginScan",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "begin_scan",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceBeginScan,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceEndScan",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "end_scan",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceEndScan,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceGet",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "get",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceGet,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceGetlist",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "getlist",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceGetlist,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceGetlistByMod",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "getlist_by_mod",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceGetlistByMod,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceIdentify",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "identify",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceIdentify,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerAct",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_act",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerAct,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerActQr",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_act_qr",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerActQr,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerBeginAssoc",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_begin_assoc",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerBeginAssoc,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerBeginScan",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_begin_scan",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerBeginScan,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerClientMgmt",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_client_mgmt",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerClientMgmt,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerClientNetdevReq",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_client_netdev_req",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerClientNetdevReq,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerDHCPDGet",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_dhcpd_get",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerDHCPDGet,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerFilePull",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_file_pull",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerFilePull,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerFilePush",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_file_push",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerFilePush,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerGet",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_get",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerGet,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerGetlist",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_getlist",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerGetlist,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerInquiry",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_inquiry",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerInquiry,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerModify",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_modify",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerModify,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerRemove",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_remove",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerRemove,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerScan",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_scan",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerScan,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceInnerUPnPGet",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "inner_upnp_get",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceInnerUPnPGet,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceModify",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "modify",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceModify,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceRemove",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "remove",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceRemove,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotdeviceScan",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotdevice",
			operation: "scan",
			call:      (*Client).AdminMobileAppIoTDeviceIotdeviceScan,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotownerGetlist",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotowner",
			operation: "getlist",
			call:      (*Client).AdminMobileAppIoTDeviceIotownerGetlist,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotprofileGetAndUpdatePwd",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotprofile",
			operation: "get_and_update_pwd",
			call:      (*Client).AdminMobileAppIoTDeviceIotprofileGetAndUpdatePwd,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotroleInnerProgramMgmt",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotrole",
			operation: "inner_program_mgmt",
			call:      (*Client).AdminMobileAppIoTDeviceIotroleInnerProgramMgmt,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotspaceAdd",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotspace",
			operation: "add",
			call:      (*Client).AdminMobileAppIoTDeviceIotspaceAdd,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotspaceGetlist",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotspace",
			operation: "getlist",
			call:      (*Client).AdminMobileAppIoTDeviceIotspaceGetlist,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotspaceModify",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotspace",
			operation: "modify",
			call:      (*Client).AdminMobileAppIoTDeviceIotspaceModify,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotspaceRemove",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotspace",
			operation: "remove",
			call:      (*Client).AdminMobileAppIoTDeviceIotspaceRemove,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotspaceRemoveNetworkDevice",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotspace",
			operation: "remove_network_device",
			call:      (*Client).AdminMobileAppIoTDeviceIotspaceRemoveNetworkDevice,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotspaceSet",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotspace",
			operation: "set",
			call:      (*Client).AdminMobileAppIoTDeviceIotspaceSet,
		},
		{
			name:      "AdminMobileAppIoTDeviceIotspaceSetNetworkDevice",
			path:      "/admin/mobile_app/iot_device",
			form:      "iotspace",
			operation: "set_network_device",
			call:      (*Client).AdminMobileAppIoTDeviceIotspaceSetNetworkDevice,
		},
		{
			name:      "AdminMobileAppIoTDeviceZigbeeFormNetwork",
			path:      "/admin/mobile_app/iot_device",
			form:      "zigbee",
			operation: "form_network",
			call:      (*Client).AdminMobileAppIoTDeviceZigbeeFormNetwork,
		},
		{
			name:      "AdminMobileAppIoTDeviceZigbeeInnerNetwork",
			path:      "/admin/mobile_app/iot_device",
			form:      "zigbee",
			operation: "inner_network",
			call:      (*Client).AdminMobileAppIoTDeviceZigbeeInnerNetwork,
		},
		{
			name:      "AdminMobileAppIoTDeviceZigbeeInnerReportSensor",
			path:      "/admin/mobile_app/iot_device",
			form:      "zigbee",
			operation: "inner_report_sensor",
			call:      (*Client).AdminMobileAppIoTDeviceZigbeeInnerReportSensor,
		},
		{
			name:      "AdminMobileAppIoTDeviceZigbeeRemoveAll",
			path:      "/admin/mobile_app/iot_device",
			form:      "zigbee",
			operation: "remove_all",
			call:      (*Client).AdminMobileAppIoTDeviceZigbeeRemoveAll,
		},
		{
			name:      "AdminMobileAppIoTDeviceZigbeeTestcmd",
			path:      "/admin/mobile_app/iot_device",
			form:      "zigbee",
			operation: "testcmd",
			call:      (*Client).AdminMobileAppIoTDeviceZigbeeTestcmd,
		},
		{
			name:      "AdminMobileAppIPTVIPTVGet",
			path:      "/admin/mobile_app/iptv",
			form:      "iptv",
			operation: "get",
			call:      (*Client).AdminMobileAppIPTVIPTVGet,
		},
		{
			name:      "AdminMobileAppIPTVIPTVSet",
			path:      "/admin/mobile_app/iptv",
			form:      "iptv",
			operation: "set",
			call:      (*Client).AdminMobileAppIPTVIPTVSet,
		},
		{
			name:      "AdminMobileAppIPv6FirewallClientRead",
			path:      "/admin/mobile_app/ipv6_firewall",
			form:      "client",
			operation: "read",
			call:      (*Client).AdminMobileAppIPv6FirewallClientRead,
		},
		{
			name:      "AdminMobileAppIPv6FirewallFirewallModify",
			path:      "/admin/mobile_app/ipv6_firewall",
			form:      "firewall",
			operation: "modify",
			call:      (*Client).AdminMobileAppIPv6FirewallFirewallModify,
		},
		{
			name:      "AdminMobileAppIPv6FirewallFirewallRead",
			path:      "/admin/mobile_app/ipv6_firewall",
			form:      "firewall",
			operation: "read",
			call:      (*Client).AdminMobileAppIPv6FirewallFirewallRead,
		},
		{
			name:      "AdminMobileAppIPv6FirewallFirewallRemove",
			path:      "/admin/mobile_app/ipv6_firewall",
			form:      "firewall",
			operation: "remove",
			call:      (*Client).AdminMobileAppIPv6FirewallFirewallRemove,
		},
		{
			name:      "AdminMobileAppIPv6FirewallFirewallWrite",
			path:      "/admin/mobile_app/ipv6_firewall",
			form:      "firewall",
			operation: "write",
			call:      (*Client).AdminMobileAppIPv6FirewallFirewallWrite,
		},
		{
			name:      "AdminMobileAppLogLoad",
			path:      "/admin/mobile_app/log",
			form:      "",
			operation: "load",
			call:      (*Client).AdminMobileAppLogLoad,
		},
		{
			name:      "AdminMobileAppLogRead",
			path:      "/admin/mobile_app/log",
			form:      "",
			operation: "read",
			call:      (*Client).AdminMobileAppLogRead,
		},
		{
			name:      "AdminMobileAppLogWrite",
			path:      "/admin/mobile_app/log",
			form:      "",
			operation: "write",
			call:      (*Client).AdminMobileAppLogWrite,
		},
		{
			name:      "AdminMobileAppLogExportFeedbackLogBuild",
			path:      "/admin/mobile_app/log_export",
			form:      "feedback_log",
			operation: "build",
			call:      (*Client).AdminMobileAppLogExportFeedbackLogBuild,
		},
		{
			name:      "AdminMobileAppMsgServerCoordinatorNotify",
			path:      "/admin/mobile_app/msg_server",
			form:      "coordinator",
			operation: "notify",
			call:      (*Client).AdminMobileAppMsgServerCoordinatorNotify,
		},
		{
			name:      "AdminMobileAppNATAlgRead",
			path:      "/admin/mobile_app/nat",
			form:      "alg",
			operation: "read",
			call:      (*Client).AdminMobileAppNATAlgRead,
		},
		{
			name:      "AdminMobileAppNATAlgWrite",
			path:      "/admin/mobile_app/nat",
			form:      "alg",
			operation: "write",
			call:      (*Client).AdminMobileAppNATAlgWrite,
		},
		{
			name:      "AdminMobileAppNATDmzRead",
			path:      "/admin/mobile_app/nat",
			form:      "dmz",
			operation: "read",
			call:      (*Client).AdminMobileAppNATDmzRead,
		},
		{
			name:      "AdminMobileAppNATDmzWrite",
			path:      "/admin/mobile_app/nat",
			form:      "dmz",
			operation: "write",
			call:      (*Client).AdminMobileAppNATDmzWrite,
		},
		{
			name:      "AdminMobileAppNATPtInsert",
			path:      "/admin/mobile_app/nat",
			form:      "pt",
			operation: "insert",
			call:      (*Client).AdminMobileAppNATPtInsert,
		},
		{
			name:      "AdminMobileAppNATPtLoad",
			path:      "/admin/mobile_app/nat",
			form:      "pt",
			operation: "load",
			call:      (*Client).AdminMobileAppNATPtLoad,
		},
		{
			name:      "AdminMobileAppNATPtRemove",
			path:      "/admin/mobile_app/nat",
			form:      "pt",
			operation: "remove",
			call:      (*Client).AdminMobileAppNATPtRemove,
		},
		{
			name:      "AdminMobileAppNATPtUpdate",
			path:      "/admin/mobile_app/nat",
			form:      "pt",
			operation: "update",
			call:      (*Client).AdminMobileAppNATPtUpdate,
		},
		{
			name:      "AdminMobileAppNATSettingRead",
			path:      "/admin/mobile_app/nat",
			form:      "setting",
			operation: "read",
			call:      (*Client).AdminMobileAppNATSettingRead,
		},
		{
			name:      "AdminMobileAppNATSettingWrite",
			path:      "/admin/mobile_app/nat",
			form:      "setting",
			operation: "write",
			call:      (*Client).AdminMobileAppNATSettingWrite,
		},
		{
			name:      "AdminMobileAppNATSipAlgRead",
			path:      "/admin/mobile_app/nat",
			form:      "sip_alg",
			operation: "read",
			call:      (*Client).AdminMobileAppNATSipAlgRead,
		},
		{
			name:      "AdminMobileAppNATSipAlgWrite",
			path:      "/admin/mobile_app/nat",
			form:      "sip_alg",
			operation: "write",
			call:      (*Client).AdminMobileAppNATSipAlgWrite,
		},
		{
			name:      "AdminMobileAppNATVsAdd",
			path:      "/admin/mobile_app/nat",
			form:      "vs",
			operation: "add",
			call:      (*Client).AdminMobileAppNATVsAdd,
		},
		{
			name:      "AdminMobileAppNATVsBatchRemove",
			path:      "/admin/mobile_app/nat",
			form:      "vs",
			operation: "batch_remove",
			call:      (*Client).AdminMobileAppNATVsBatchRemove,
		},
		{
			name:      "AdminMobileAppNATVsGetlist",
			path:      "/admin/mobile_app/nat",
			form:      "vs",
			operation: "getlist",
			call:      (*Client).AdminMobileAppNATVsGetlist,
		},
		{
			name:      "AdminMobileAppNATVsModify",
			path:      "/admin/mobile_app/nat",
			form:      "vs",
			operation: "modify",
			call:      (*Client).AdminMobileAppNATVsModify,
		},
		{
			name:      "AdminMobileAppNATVsRead",
			path:      "/admin/mobile_app/nat",
			form:      "vs",
			operation: "read",
			call:      (*Client).AdminMobileAppNATVsRead,
		},
		{
			name:      "AdminMobileAppNATVsRemove",
			path:      "/admin/mobile_app/nat",
			form:      "vs",
			operation: "remove",
			call:      (*Client).AdminMobileAppNATVsRemove,
		},
		{
			name:      "AdminMobileAppNetworkInternetRead",
			path:      "/admin/mobile_app/network",
			form:      "internet",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkInternetRead,
		},
		{
			name:      "AdminMobileAppNetworkInternetWrite",
			path:      "/admin/mobile_app/network",
			form:      "internet",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkInternetWrite,
		},
		{
			name:      "AdminMobileAppNetworkIPv6Read",
			path:      "/admin/mobile_app/network",
			form:      "ipv6",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkIPv6Read,
		},
		{
			name:      "AdminMobileAppNetworkIPv6Write",
			path:      "/admin/mobile_app/network",
			form:      "ipv6",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkIPv6Write,
		},
		{
			name:      "AdminMobileAppNetworkLANBlockRead",
			path:      "/admin/mobile_app/network",
			form:      "lan_block",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkLANBlockRead,
		},
		{
			name:      "AdminMobileAppNetworkLANBlockWrite",
			path:      "/admin/mobile_app/network",
			form:      "lan_block",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkLANBlockWrite,
		},
		{
			name:      "AdminMobileAppNetworkLANIPRead",
			path:      "/admin/mobile_app/network",
			form:      "lan_ip",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkLANIPRead,
		},
		{
			name:      "AdminMobileAppNetworkLANIPWrite",
			path:      "/admin/mobile_app/network",
			form:      "lan_ip",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkLANIPWrite,
		},
		{
			name:      "AdminMobileAppNetworkLANIPv4Read",
			path:      "/admin/mobile_app/network",
			form:      "lan_ipv4",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkLANIPv4Read,
		},
		{
			name:      "AdminMobileAppNetworkLANIPv4Write",
			path:      "/admin/mobile_app/network",
			form:      "lan_ipv4",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkLANIPv4Write,
		},
		{
			name:      "AdminMobileAppNetworkMACCloneRead",
			path:      "/admin/mobile_app/network",
			form:      "mac_clone",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkMACCloneRead,
		},
		{
			name:      "AdminMobileAppNetworkMACCloneWrite",
			path:      "/admin/mobile_app/network",
			form:      "mac_clone",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkMACCloneWrite,
		},
		{
			name:      "AdminMobileAppNetworkMACCloneListRead",
			path:      "/admin/mobile_app/network",
			form:      "mac_clone_list",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkMACCloneListRead,
		},
		{
			name:      "AdminMobileAppNetworkRoutesStaticAdd",
			path:      "/admin/mobile_app/network",
			form:      "routes_static",
			operation: "add",
			call:      (*Client).AdminMobileAppNetworkRoutesStaticAdd,
		},
		{
			name:      "AdminMobileAppNetworkRoutesStaticGetlist",
			path:      "/admin/mobile_app/network",
			form:      "routes_static",
			operation: "getlist",
			call:      (*Client).AdminMobileAppNetworkRoutesStaticGetlist,
		},
		{
			name:      "AdminMobileAppNetworkRoutesStaticModify",
			path:      "/admin/mobile_app/network",
			form:      "routes_static",
			operation: "modify",
			call:      (*Client).AdminMobileAppNetworkRoutesStaticModify,
		},
		{
			name:      "AdminMobileAppNetworkRoutesStaticRemove",
			path:      "/admin/mobile_app/network",
			form:      "routes_static",
			operation: "remove",
			call:      (*Client).AdminMobileAppNetworkRoutesStaticRemove,
		},
		{
			name:      "AdminMobileAppNetworkRoutesSystemGetlist",
			path:      "/admin/mobile_app/network",
			form:      "routes_system",
			operation: "getlist",
			call:      (*Client).AdminMobileAppNetworkRoutesSystemGetlist,
		},
		{
			name:      "AdminMobileAppNetworkUPnPRead",
			path:      "/admin/mobile_app/network",
			form:      "upnp",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkUPnPRead,
		},
		{
			name:      "AdminMobileAppNetworkUPnPWrite",
			path:      "/admin/mobile_app/network",
			form:      "upnp",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkUPnPWrite,
		},
		{
			name:      "AdminMobileAppNetworkVLANRead",
			path:      "/admin/mobile_app/network",
			form:      "vlan",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkVLANRead,
		},
		{
			name:      "AdminMobileAppNetworkVLANWrite",
			path:      "/admin/mobile_app/network",
			form:      "vlan",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkVLANWrite,
		},
		{
			name:      "AdminMobileAppNetworkWANIPv4Connect",
			path:      "/admin/mobile_app/network",
			form:      "wan_ipv4",
			operation: "connect",
			call:      (*Client).AdminMobileAppNetworkWANIPv4Connect,
		},
		{
			name:      "AdminMobileAppNetworkWANIPv4Disconnect",
			path:      "/admin/mobile_app/network",
			form:      "wan_ipv4",
			operation: "disconnect",
			call:      (*Client).AdminMobileAppNetworkWANIPv4Disconnect,
		},
		{
			name:      "AdminMobileAppNetworkWANIPv4Read",
			path:      "/admin/mobile_app/network",
			form:      "wan_ipv4",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkWANIPv4Read,
		},
		{
			name:      "AdminMobileAppNetworkWANIPv4Write",
			path:      "/admin/mobile_app/network",
			form:      "wan_ipv4",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkWANIPv4Write,
		},
		{
			name:      "AdminMobileAppNetworkWANModeRead",
			path:      "/admin/mobile_app/network",
			form:      "wan_mode",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkWANModeRead,
		},
		{
			name:      "AdminMobileAppNetworkWANModeWrite",
			path:      "/admin/mobile_app/network",
			form:      "wan_mode",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkWANModeWrite,
		},
		{
			name:      "AdminMobileAppNetworkOptimizeACSFilterMacsGet",
			path:      "/admin/mobile_app/network_optimize",
			form:      "acs_filter_macs",
			operation: "get",
			call:      (*Client).AdminMobileAppNetworkOptimizeACSFilterMacsGet,
		},
		{
			name:      "AdminMobileAppNetworkOptimizeACSOptimizeRead",
			path:      "/admin/mobile_app/network_optimize",
			form:      "acs_optimize",
			operation: "read",
			call:      (*Client).AdminMobileAppNetworkOptimizeACSOptimizeRead,
		},
		{
			name:      "AdminMobileAppNetworkOptimizeACSOptimizeWrite",
			path:      "/admin/mobile_app/network_optimize",
			form:      "acs_optimize",
			operation: "write",
			call:      (*Client).AdminMobileAppNetworkOptimizeACSOptimizeWrite,
		},
		{
			name:      "AdminMobileAppNRDBlackListBlock",
			path:      "/admin/mobile_app/nrd",
			form:      "black_list",
			operation: "block",
			call:      (*Client).AdminMobileAppNRDBlackListBlock,
		},
		{
			name:      "AdminMobileAppNRDBlackListList",
			path:      "/admin/mobile_app/nrd",
			form:      "black_list",
			operation: "list",
			call:      (*Client).AdminMobileAppNRDBlackListList,
		},
		{
			name:      "AdminMobileAppNRDBlackListUnblock",
			path:      "/admin/mobile_app/nrd",
			form:      "black_list",
			operation: "unblock",
			call:      (*Client).AdminMobileAppNRDBlackListUnblock,
		},
		{
			name:      "AdminMobileAppPrivacyPolicyPrivacyPolicyRead",
			path:      "/admin/mobile_app/privacy_policy",
			form:      "privacy_policy",
			operation: "read",
			call:      (*Client).AdminMobileAppPrivacyPolicyPrivacyPolicyRead,
		},
		{
			name:      "AdminMobileAppPrivacyPolicyPrivacyPolicyWrite",
			path:      "/admin/mobile_app/privacy_policy",
			form:      "privacy_policy",
			operation: "write",
			call:      (*Client).AdminMobileAppPrivacyPolicyPrivacyPolicyWrite,
		},
		{
			name:      "AdminMobileAppQuickSetupBatchdevicesRead",
			path:      "/admin/mobile_app/quick_setup",
			form:      "batchdevices",
			operation: "read",
			call:      (*Client).AdminMobileAppQuickSetupBatchdevicesRead,
		},
		{
			name:      "AdminMobileAppQuickSetupBatchdevicesWrite",
			path:      "/admin/mobile_app/quick_setup",
			form:      "batchdevices",
			operation: "write",
			call:      (*Client).AdminMobileAppQuickSetupBatchdevicesWrite,
		},
		{
			name:      "AdminMobileAppQuickSetupBluetoothRead",
			path:      "/admin/mobile_app/quick_setup",
			form:      "bluetooth",
			operation: "read",
			call:      (*Client).AdminMobileAppQuickSetupBluetoothRead,
		},
		{
			name:      "AdminMobileAppQuickSetupBluetoothWrite",
			path:      "/admin/mobile_app/quick_setup",
			form:      "bluetooth",
			operation: "write",
			call:      (*Client).AdminMobileAppQuickSetupBluetoothWrite,
		},
		{
			name:      "AdminMobileAppQuickSetupDcmpPreConfigPreConfigWrite",
			path:      "/admin/mobile_app/quick_setup",
			form:      "dcmp_pre_config",
			operation: "pre_config_write",
			call:      (*Client).AdminMobileAppQuickSetupDcmpPreConfigPreConfigWrite,
		},
		{
			name:      "AdminMobileAppQuickSetupDcmpPreConfigSavePreConfig",
			path:      "/admin/mobile_app/quick_setup",
			form:      "dcmp_pre_config",
			operation: "save_pre_config",
			call:      (*Client).AdminMobileAppQuickSetupDcmpPreConfigSavePreConfig,
		},
		{
			name:      "AdminMobileAppQuickSetupEponymousDetectWrite",
			path:      "/admin/mobile_app/quick_setup",
			form:      "eponymous_detect",
			operation: "write",
			call:      (*Client).AdminMobileAppQuickSetupEponymousDetectWrite,
		},
		{
			name:      "AdminMobileAppQuickSetupHeartbeatRead",
			path:      "/admin/mobile_app/quick_setup",
			form:      "heartbeat",
			operation: "read",
			call:      (*Client).AdminMobileAppQuickSetupHeartbeatRead,
		},
		{
			name:      "AdminMobileAppQuickSetupHeartbeatSync",
			path:      "/admin/mobile_app/quick_setup",
			form:      "heartbeat",
			operation: "sync",
			call:      (*Client).AdminMobileAppQuickSetupHeartbeatSync,
		},
		{
			name:      "AdminMobileAppQuickSetupNewdeviceWrite",
			path:      "/admin/mobile_app/quick_setup",
			form:      "newdevice",
			operation: "write",
			call:      (*Client).AdminMobileAppQuickSetupNewdeviceWrite,
		},
		{
			name:      "AdminMobileAppQuickSetupNewgroupWrite",
			path:      "/admin/mobile_app/quick_setup",
			form:      "newgroup",
			operation: "write",
			call:      (*Client).AdminMobileAppQuickSetupNewgroupWrite,
		},
		{
			name:      "AdminMobileAppQuickSetupPreconfPreconfAdd",
			path:      "/admin/mobile_app/quick_setup",
			form:      "preconf",
			operation: "preconf_add",
			call:      (*Client).AdminMobileAppQuickSetupPreconfPreconfAdd,
		},
		{
			name:      "AdminMobileAppQuickSetupPreconfPreconfCheck",
			path:      "/admin/mobile_app/quick_setup",
			form:      "preconf",
			operation: "preconf_check",
			call:      (*Client).AdminMobileAppQuickSetupPreconfPreconfCheck,
		},
		{
			name:      "AdminMobileAppQuickSetupPreconfPreconfRead",
			path:      "/admin/mobile_app/quick_setup",
			form:      "preconf",
			operation: "preconf_read",
			call:      (*Client).AdminMobileAppQuickSetupPreconfPreconfRead,
		},
		{
			name:      "AdminMobileAppQuickSetupPreconfPreconfWrite",
			path:      "/admin/mobile_app/quick_setup",
			form:      "preconf",
			operation: "preconf_write",
			call:      (*Client).AdminMobileAppQuickSetupPreconfPreconfWrite,
		},
		{
			name:      "AdminMobileAppSecurityCategoryRead",
			path:      "/admin/mobile_app/security",
			form:      "category",
			operation: "read",
			call:      (*Client).AdminMobileAppSecurityCategoryRead,
		},
		{
			name:      "AdminMobileAppSecurityHistoryClear",
			path:      "/admin/mobile_app/security",
			form:      "history",
			operation: "clear",
			call:      (*Client).AdminMobileAppSecurityHistoryClear,
		},
		{
			name:      "AdminMobileAppSecurityHistoryGet",
			path:      "/admin/mobile_app/security",
			form:      "history",
			operation: "get",
			call:      (*Client).AdminMobileAppSecurityHistoryGet,
		},
		{
			name:      "AdminMobileAppSecurityHistoryRemove",
			path:      "/admin/mobile_app/security",
			form:      "history",
			operation: "remove",
			call:      (*Client).AdminMobileAppSecurityHistoryRemove,
		},
		{
			name:      "AdminMobileAppSecurityInfoRead",
			path:      "/admin/mobile_app/security",
			form:      "info",
			operation: "read",
			call:      (*Client).AdminMobileAppSecurityInfoRead,
		},
		{
			name:      "AdminMobileAppSecurityInfoWrite",
			path:      "/admin/mobile_app/security",
			form:      "info",
			operation: "write",
			call:      (*Client).AdminMobileAppSecurityInfoWrite,
		},
		{
			name:      "AdminMobileAppSecurityRuleRead",
			path:      "/admin/mobile_app/security",
			form:      "rule",
			operation: "read",
			call:      (*Client).AdminMobileAppSecurityRuleRead,
		},
		{
			name:      "AdminMobileAppSecurityRuleUpdate",
			path:      "/admin/mobile_app/security",
			form:      "rule",
			operation: "update",
			call:      (*Client).AdminMobileAppSecurityRuleUpdate,
		},
		{
			name:      "AdminMobileAppSmartNetworkAppBlockListGet",
			path:      "/admin/mobile_app/smart_network",
			form:      "app_block_list",
			operation: "get",
			call:      (*Client).AdminMobileAppSmartNetworkAppBlockListGet,
		},
		{
			name:      "AdminMobileAppSmartNetworkAppDPITimeLimitAdd",
			path:      "/admin/mobile_app/smart_network",
			form:      "app_dpi",
			operation: "time_limit_add",
			call:      (*Client).AdminMobileAppSmartNetworkAppDPITimeLimitAdd,
		},
		{
			name:      "AdminMobileAppSmartNetworkAppDPITimeLimitModify",
			path:      "/admin/mobile_app/smart_network",
			form:      "app_dpi",
			operation: "time_limit_modify",
			call:      (*Client).AdminMobileAppSmartNetworkAppDPITimeLimitModify,
		},
		{
			name:      "AdminMobileAppSmartNetworkAppDPITimeLimitRemove",
			path:      "/admin/mobile_app/smart_network",
			form:      "app_dpi",
			operation: "time_limit_remove",
			call:      (*Client).AdminMobileAppSmartNetworkAppDPITimeLimitRemove,
		},
		{
			name:      "AdminMobileAppSmartNetworkAppQoSGet",
			path:      "/admin/mobile_app/smart_network",
			form:      "app_qos",
			operation: "get",
			call:      (*Client).AdminMobileAppSmartNetworkAppQoSGet,
		},
		{
			name:      "AdminMobileAppSmartNetworkAppQoSRemove",
			path:      "/admin/mobile_app/smart_network",
			form:      "app_qos",
			operation: "remove",
			call:      (*Client).AdminMobileAppSmartNetworkAppQoSRemove,
		},
		{
			name:      "AdminMobileAppSmartNetworkAppQoSSet",
			path:      "/admin/mobile_app/smart_network",
			form:      "app_qos",
			operation: "set",
			call:      (*Client).AdminMobileAppSmartNetworkAppQoSSet,
		},
		{
			name:      "AdminMobileAppSmartNetworkBandwidthGet",
			path:      "/admin/mobile_app/smart_network",
			form:      "bandwidth",
			operation: "get",
			call:      (*Client).AdminMobileAppSmartNetworkBandwidthGet,
		},
		{
			name:      "AdminMobileAppSmartNetworkBandwidthSet",
			path:      "/admin/mobile_app/smart_network",
			form:      "bandwidth",
			operation: "set",
			call:      (*Client).AdminMobileAppSmartNetworkBandwidthSet,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlAddAppTimeLimit",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "addAppTimeLimit",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlAddAppTimeLimit,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlAddOwnerInList",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "addOwnerInList",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlAddOwnerInList,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlAddWhiteList",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "addWhiteList",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlAddWhiteList,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlDelActHistory",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "delActHistory",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlDelActHistory,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlDelAppTimeLimit",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "delAppTimeLimit",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlDelAppTimeLimit,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlDelOwnerInList",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "delOwnerInList",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlDelOwnerInList,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlDelWhiteList",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "delWhiteList",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlDelWhiteList,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlGetActHistory",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "getActHistory",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlGetActHistory,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlGetAppBlockList",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "getAppBlockList",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlGetAppBlockList,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlGetInsightData",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "getInsightData",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlGetInsightData,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlGetOwner",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "getOwner",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlGetOwner,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlGetOwnerInList",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "getOwnerInList",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlGetOwnerInList,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlIgnoreReq",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "ignoreReq",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlIgnoreReq,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlModifyAppTimeLimit",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "modifyAppTimeLimit",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlModifyAppTimeLimit,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlModifyBaseInfo",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "modifyBaseInfo",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlModifyBaseInfo,
		},
		{
			name:      "AdminMobileAppSmartNetworkHCUpgPctlSetBonusTime",
			path:      "/admin/mobile_app/smart_network",
			form:      "hc_upg_pctl",
			operation: "setBonusTime",
			call:      (*Client).AdminMobileAppSmartNetworkHCUpgPctlSetBonusTime,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolCliAdd",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_cli",
			operation: "add",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolCliAdd,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolCliDel",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_cli",
			operation: "del",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolCliDel,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolFilterBlock",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_filter",
			operation: "block",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolFilterBlock,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolFilterList",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_filter",
			operation: "list",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolFilterList,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolFilterTable",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_filter",
			operation: "table",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolFilterTable,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolFilterUnblock",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_filter",
			operation: "unblock",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolFilterUnblock,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolInsightsGet",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_insights",
			operation: "get",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolInsightsGet,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolInsightsHistory",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_insights",
			operation: "history",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolInsightsHistory,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolInsightsRemove",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_insights",
			operation: "remove",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolInsightsRemove,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolOwnerAdd",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_owner",
			operation: "add",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolOwnerAdd,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolOwnerBlock",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_owner",
			operation: "block",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolOwnerBlock,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolOwnerDel",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_owner",
			operation: "del",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolOwnerDel,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolOwnerGet",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_owner",
			operation: "get",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolOwnerGet,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolOwnerList",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_owner",
			operation: "list",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolOwnerList,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolOwnerSet",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_owner",
			operation: "set",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolOwnerSet,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolOwnerAvatarGet",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_owner_avatar",
			operation: "get",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolOwnerAvatarGet,
		},
		{
			name:      "AdminMobileAppSmartNetworkPatrolOwnerAvatarSet",
			path:      "/admin/mobile_app/smart_network",
			form:      "patrol_owner_avatar",
			operation: "set",
			call:      (*Client).AdminMobileAppSmartNetworkPatrolOwnerAvatarSet,
		},
		{
			name:      "AdminMobileAppSmartNetworkTMQoSRead",
			path:      "/admin/mobile_app/smart_network",
			form:      "tm_qos",
			operation: "read",
			call:      (*Client).AdminMobileAppSmartNetworkTMQoSRead,
		},
		{
			name:      "AdminMobileAppSmartNetworkTMQoSWrite",
			path:      "/admin/mobile_app/smart_network",
			form:      "tm_qos",
			operation: "write",
			call:      (*Client).AdminMobileAppSmartNetworkTMQoSWrite,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraAddOwnerInList",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "addOwnerInList",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraAddOwnerInList,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraAddAllowedWebsites",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "add_allowed_websites",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraAddAllowedWebsites,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraAddSecWhitelist",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "add_sec_whitelist",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraAddSecWhitelist,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraBonusTimeSet",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "bonusTimeSet",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraBonusTimeSet,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraCloudServiceStateCheck",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "cloud_service_state_check",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraCloudServiceStateCheck,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraDelOwnerInList",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "delOwnerInList",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraDelOwnerInList,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraGetFamilyTimeInfo",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "getFamilyTimeInfo",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraGetFamilyTimeInfo,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraGetInsightData",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "getInsightData",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraGetInsightData,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraGetOwnerInList",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "getOwnerInList",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraGetOwnerInList,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraGetTodayInsightTimeUsagePro",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "getTodayInsightTimeUsagePro",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraGetTodayInsightTimeUsagePro,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraGetAllowedWebsites",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "get_allowed_websites",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraGetAllowedWebsites,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraGetSecWhitelist",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "get_sec_whitelist",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraGetSecWhitelist,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraIgnoreReq",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "ignoreReq",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraIgnoreReq,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraISPGet",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "ispGet",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraISPGet,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraModifyBaseInfo",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "modifyBaseInfo",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraModifyBaseInfo,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraNetworkQualityStartOptimize",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "networkQualityStartOptimize",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraNetworkQualityStartOptimize,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraOwnerClientListSet",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "ownerClientListSet",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraOwnerClientListSet,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraRemoveAllowedWebsites",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "remove_allowed_websites",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraRemoveAllowedWebsites,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraRemoveSecWhitelist",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "remove_sec_whitelist",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraRemoveSecWhitelist,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraScanGet",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "scanGet",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraScanGet,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraScanStart",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "scanStart",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraScanStart,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraScanStop",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "scanStop",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraScanStop,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraServiceStateCheck",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "service_state_check",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraServiceStateCheck,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraServiceStatusCheck",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "service_status_check",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraServiceStatusCheck,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraSetFamilyTimeInfo",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "setFamilyTimeInfo",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraSetFamilyTimeInfo,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraTmpGetSecinfo",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "tmp_get_secinfo",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraTmpGetSecinfo,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraTmpGetSecv2info",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "tmp_get_secv2info",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraTmpGetSecv2info,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraTmpSetSecinfo",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "tmp_set_secinfo",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraTmpSetSecinfo,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraTmpSetSecv2info",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "tmp_set_secv2info",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraTmpSetSecv2info,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraWhiteListAdd",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "white_list_add",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraWhiteListAdd,
		},
		{
			name:      "AdminMobileAppSmartNetworkTmpAviraWhiteListRemove",
			path:      "/admin/mobile_app/smart_network",
			form:      "tmp_avira",
			operation: "white_list_remove",
			call:      (*Client).AdminMobileAppSmartNetworkTmpAviraWhiteListRemove,
		},
		{
			name:      "AdminMobileAppSmartNetworkWhiteListAdd",
			path:      "/admin/mobile_app/smart_network",
			form:      "white_list",
			operation: "add",
			call:      (*Client).AdminMobileAppSmartNetworkWhiteListAdd,
		},
		{
			name:      "AdminMobileAppSmartNetworkWhiteListGet",
			path:      "/admin/mobile_app/smart_network",
			form:      "white_list",
			operation: "get",
			call:      (*Client).AdminMobileAppSmartNetworkWhiteListGet,
		},
		{
			name:      "AdminMobileAppSmartNetworkWhiteListRemove",
			path:      "/admin/mobile_app/smart_network",
			form:      "white_list",
			operation: "remove",
			call:      (*Client).AdminMobileAppSmartNetworkWhiteListRemove,
		},
		{
			name:      "AdminMobileAppVPNClientConfigRead",
			path:      "/admin/mobile_app/vpn_client",
			form:      "config",
			operation: "read",
			call:      (*Client).AdminMobileAppVPNClientConfigRead,
		},
		{
			name:      "AdminMobileAppVPNClientConfigWrite",
			path:      "/admin/mobile_app/vpn_client",
			form:      "config",
			operation: "write",
			call:      (*Client).AdminMobileAppVPNClientConfigWrite,
		},
		{
			name:      "AdminMobileAppVPNClientServerInsert",
			path:      "/admin/mobile_app/vpn_client",
			form:      "server",
			operation: "insert",
			call:      (*Client).AdminMobileAppVPNClientServerInsert,
		},
		{
			name:      "AdminMobileAppVPNClientServerLoad",
			path:      "/admin/mobile_app/vpn_client",
			form:      "server",
			operation: "load",
			call:      (*Client).AdminMobileAppVPNClientServerLoad,
		},
		{
			name:      "AdminMobileAppVPNClientServerRemove",
			path:      "/admin/mobile_app/vpn_client",
			form:      "server",
			operation: "remove",
			call:      (*Client).AdminMobileAppVPNClientServerRemove,
		},
		{
			name:      "AdminMobileAppVPNClientServerUpdate",
			path:      "/admin/mobile_app/vpn_client",
			form:      "server",
			operation: "update",
			call:      (*Client).AdminMobileAppVPNClientServerUpdate,
		},
		{
			name:      "AdminMobileAppVPNServerAccountsInsert",
			path:      "/admin/mobile_app/vpn_server",
			form:      "accounts",
			operation: "insert",
			call:      (*Client).AdminMobileAppVPNServerAccountsInsert,
		},
		{
			name:      "AdminMobileAppVPNServerAccountsRemove",
			path:      "/admin/mobile_app/vpn_server",
			form:      "accounts",
			operation: "remove",
			call:      (*Client).AdminMobileAppVPNServerAccountsRemove,
		},
		{
			name:      "AdminMobileAppVPNServerAccountsUpdate",
			path:      "/admin/mobile_app/vpn_server",
			form:      "accounts",
			operation: "update",
			call:      (*Client).AdminMobileAppVPNServerAccountsUpdate,
		},
		{
			name:      "AdminMobileAppVPNServerCertCheck",
			path:      "/admin/mobile_app/vpn_server",
			form:      "cert",
			operation: "check",
			call:      (*Client).AdminMobileAppVPNServerCertCheck,
		},
		{
			name:      "AdminMobileAppVPNServerCertSet",
			path:      "/admin/mobile_app/vpn_server",
			form:      "cert",
			operation: "set",
			call:      (*Client).AdminMobileAppVPNServerCertSet,
		},
		{
			name:      "AdminMobileAppVPNServerServerInsert",
			path:      "/admin/mobile_app/vpn_server",
			form:      "server",
			operation: "insert",
			call:      (*Client).AdminMobileAppVPNServerServerInsert,
		},
		{
			name:      "AdminMobileAppVPNServerServerRead",
			path:      "/admin/mobile_app/vpn_server",
			form:      "server",
			operation: "read",
			call:      (*Client).AdminMobileAppVPNServerServerRead,
		},
		{
			name:      "AdminMobileAppVPNServerServerRemove",
			path:      "/admin/mobile_app/vpn_server",
			form:      "server",
			operation: "remove",
			call:      (*Client).AdminMobileAppVPNServerServerRemove,
		},
		{
			name:      "AdminMobileAppVPNServerServerUpdate",
			path:      "/admin/mobile_app/vpn_server",
			form:      "server",
			operation: "update",
			call:      (*Client).AdminMobileAppVPNServerServerUpdate,
		},
		{
			name:      "AdminMobileAppVPNServerSingleRead",
			path:      "/admin/mobile_app/vpn_server",
			form:      "single",
			operation: "read",
			call:      (*Client).AdminMobileAppVPNServerSingleRead,
		},
		{
			name:      "AdminMobileAppVpnconnCertSync",
			path:      "/admin/mobile_app/vpnconn",
			form:      "cert",
			operation: "sync",
			call:      (*Client).AdminMobileAppVpnconnCertSync,
		},
		{
			name:      "AdminMobileAppVpnconnConnDisconnect",
			path:      "/admin/mobile_app/vpnconn",
			form:      "conn",
			operation: "disconnect",
			call:      (*Client).AdminMobileAppVpnconnConnDisconnect,
		},
		{
			name:      "AdminMobileAppVpnconnConnList",
			path:      "/admin/mobile_app/vpnconn",
			form:      "conn",
			operation: "list",
			call:      (*Client).AdminMobileAppVpnconnConnList,
		},
		{
			name:      "AdminMobileAppWirelessBandwidthEnhanceRead",
			path:      "/admin/mobile_app/wireless",
			form:      "bandwidth_enhance",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessBandwidthEnhanceRead,
		},
		{
			name:      "AdminMobileAppWirelessBandwidthEnhanceWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "bandwidth_enhance",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessBandwidthEnhanceWrite,
		},
		{
			name:      "AdminMobileAppWirelessBandwidthSwitchCheck",
			path:      "/admin/mobile_app/wireless",
			form:      "bandwidth_switch",
			operation: "check",
			call:      (*Client).AdminMobileAppWirelessBandwidthSwitchCheck,
		},
		{
			name:      "AdminMobileAppWirelessBandwidthSwitchRead",
			path:      "/admin/mobile_app/wireless",
			form:      "bandwidth_switch",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessBandwidthSwitchRead,
		},
		{
			name:      "AdminMobileAppWirelessBandwidthSwitchWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "bandwidth_switch",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessBandwidthSwitchWrite,
		},
		{
			name:      "AdminMobileAppWirelessBeamformingRead",
			path:      "/admin/mobile_app/wireless",
			form:      "beamforming",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessBeamformingRead,
		},
		{
			name:      "AdminMobileAppWirelessBeamformingWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "beamforming",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessBeamformingWrite,
		},
		{
			name:      "AdminMobileAppWirelessBridgeCheck",
			path:      "/admin/mobile_app/wireless",
			form:      "bridge",
			operation: "check",
			call:      (*Client).AdminMobileAppWirelessBridgeCheck,
		},
		{
			name:      "AdminMobileAppWirelessBridgeRead",
			path:      "/admin/mobile_app/wireless",
			form:      "bridge",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessBridgeRead,
		},
		{
			name:      "AdminMobileAppWirelessDedicatedBackhaulRead",
			path:      "/admin/mobile_app/wireless",
			form:      "dedicated_backhaul",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessDedicatedBackhaulRead,
		},
		{
			name:      "AdminMobileAppWirelessDedicatedBackhaulWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "dedicated_backhaul",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessDedicatedBackhaulWrite,
		},
		{
			name:      "AdminMobileAppWirelessIeee80211rRead",
			path:      "/admin/mobile_app/wireless",
			form:      "ieee80211r",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessIeee80211rRead,
		},
		{
			name:      "AdminMobileAppWirelessIeee80211rWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "ieee80211r",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessIeee80211rWrite,
		},
		{
			name:      "AdminMobileAppWirelessOperationModeRead",
			path:      "/admin/mobile_app/wireless",
			form:      "operation_mode",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessOperationModeRead,
		},
		{
			name:      "AdminMobileAppWirelessOperationModeWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "operation_mode",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessOperationModeWrite,
		},
		{
			name:      "AdminMobileAppWirelessPowerWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "power",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessPowerWrite,
		},
		{
			name:      "AdminMobileAppWirelessSmartAntennaRead",
			path:      "/admin/mobile_app/wireless",
			form:      "smart_antenna",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessSmartAntennaRead,
		},
		{
			name:      "AdminMobileAppWirelessSmartAntennaWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "smart_antenna",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessSmartAntennaWrite,
		},
		{
			name:      "AdminMobileAppWirelessWiFiScheduleRead",
			path:      "/admin/mobile_app/wireless",
			form:      "wifi_schedule",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessWiFiScheduleRead,
		},
		{
			name:      "AdminMobileAppWirelessWiFiScheduleWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "wifi_schedule",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessWiFiScheduleWrite,
		},
		{
			name:      "AdminMobileAppWirelessWLANRead",
			path:      "/admin/mobile_app/wireless",
			form:      "wlan",
			operation: "read",
			call:      (*Client).AdminMobileAppWirelessWLANRead,
		},
		{
			name:      "AdminMobileAppWirelessWLANWrite",
			path:      "/admin/mobile_app/wireless",
			form:      "wlan",
			operation: "write",
			call:      (*Client).AdminMobileAppWirelessWLANWrite,
		},
		{
			name:      "AdminMobileAppWPSStateSet",
			path:      "/admin/mobile_app/wps",
			form:      "state",
			operation: "set",
			call:      (*Client).AdminMobileAppWPSStateSet,
		},
		{
			name:      "AdminMobileAppWPSStatusGet",
			path:      "/admin/mobile_app/wps",
			form:      "status",
			operation: "get",
			call:      (*Client).AdminMobileAppWPSStatusGet,
		},
	})
}
