package deco

import "testing"

func TestAdminCloudAccountMethods(t *testing.T) {
	testAdminMethodCases(t, []adminMethodCase{
		{
			name:      "AdminCloudAccountCheckCloudConnectionRead",
			path:      "/admin/cloud_account",
			form:      "check_cloud_connection",
			operation: "read",
			call:      (*Client).AdminCloudAccountCheckCloudConnectionRead,
		},
		{
			name:      "AdminCloudAccountCheckCloudVersionRead",
			path:      "/admin/cloud_account",
			form:      "check_cloud_version",
			operation: "read",
			call:      (*Client).AdminCloudAccountCheckCloudVersionRead,
		},
		{
			name:      "AdminCloudAccountCheckConnectionRead",
			path:      "/admin/cloud_account",
			form:      "check_connection",
			operation: "read",
			call:      (*Client).AdminCloudAccountCheckConnectionRead,
		},
		{
			name:      "AdminCloudAccountCheckDeviceRead",
			path:      "/admin/cloud_account",
			form:      "check_device",
			operation: "read",
			call:      (*Client).AdminCloudAccountCheckDeviceRead,
		},
		{
			name:      "AdminCloudAccountCheckInternetRead",
			path:      "/admin/cloud_account",
			form:      "check_internet",
			operation: "read",
			call:      (*Client).AdminCloudAccountCheckInternetRead,
		},
		{
			name:      "AdminCloudAccountCheckLoginRead",
			path:      "/admin/cloud_account",
			form:      "check_login",
			operation: "read",
			call:      (*Client).AdminCloudAccountCheckLoginRead,
		},
		{
			name:      "AdminCloudAccountCheckSupportRead",
			path:      "/admin/cloud_account",
			form:      "check_support",
			operation: "read",
			call:      (*Client).AdminCloudAccountCheckSupportRead,
		},
		{
			name:      "AdminCloudAccountCheckUpgradeRead",
			path:      "/admin/cloud_account",
			form:      "check_upgrade",
			operation: "read",
			call:      (*Client).AdminCloudAccountCheckUpgradeRead,
		},
		{
			name:      "AdminCloudAccountCloudUnbindWrite",
			path:      "/admin/cloud_account",
			form:      "cloud_unbind",
			operation: "write",
			call:      (*Client).AdminCloudAccountCloudUnbindWrite,
		},
		{
			name:      "AdminCloudAccountCloudUpgradeLoad",
			path:      "/admin/cloud_account",
			form:      "cloud_upgrade",
			operation: "load",
			call:      (*Client).AdminCloudAccountCloudUpgradeLoad,
		},
		{
			name:      "AdminCloudAccountCloudUpgradeRead",
			path:      "/admin/cloud_account",
			form:      "cloud_upgrade",
			operation: "read",
			call:      (*Client).AdminCloudAccountCloudUpgradeRead,
		},
		{
			name:      "AdminCloudAccountCloudUpgradeUpgrade",
			path:      "/admin/cloud_account",
			form:      "cloud_upgrade",
			operation: "upgrade",
			call:      (*Client).AdminCloudAccountCloudUpgradeUpgrade,
		},
		{
			name:      "AdminCloudAccountDetectUpgradeStatusRead",
			path:      "/admin/cloud_account",
			form:      "detect_upgrade_status",
			operation: "read",
			call:      (*Client).AdminCloudAccountDetectUpgradeStatusRead,
		},
		{
			name:      "AdminCloudAccountGetDeviceInfoRead",
			path:      "/admin/cloud_account",
			form:      "get_deviceInfo",
			operation: "read",
			call:      (*Client).AdminCloudAccountGetDeviceInfoRead,
		},
		{
			name:      "AdminCloudAccountGetTokenRead",
			path:      "/admin/cloud_account",
			form:      "get_token",
			operation: "read",
			call:      (*Client).AdminCloudAccountGetTokenRead,
		},
		{
			name:      "AdminCloudAccountModifyCloudPwdWrite",
			path:      "/admin/cloud_account",
			form:      "modify_cloud_pwd",
			operation: "write",
			call:      (*Client).AdminCloudAccountModifyCloudPwdWrite,
		},
		{
			name:      "AdminCloudAccountSetShowFlagWrite",
			path:      "/admin/cloud_account",
			form:      "set_show_flag",
			operation: "write",
			call:      (*Client).AdminCloudAccountSetShowFlagWrite,
		},
		{
			name:      "AdminCloudAccountTmpCmdBindOwner",
			path:      "/admin/cloud_account",
			form:      "tmp_cmd",
			operation: "bind_owner",
			call:      (*Client).AdminCloudAccountTmpCmdBindOwner,
		},
		{
			name:      "AdminCloudAccountTmpCmdCloudPassThrough",
			path:      "/admin/cloud_account",
			form:      "tmp_cmd",
			operation: "cloud_pass_through",
			call:      (*Client).AdminCloudAccountTmpCmdCloudPassThrough,
		},
		{
			name:      "AdminCloudAccountTmpCmdGetDevInfo",
			path:      "/admin/cloud_account",
			form:      "tmp_cmd",
			operation: "get_dev_info",
			call:      (*Client).AdminCloudAccountTmpCmdGetDevInfo,
		},
		{
			name:      "AdminCloudAccountTmpCmdSetDevInfo",
			path:      "/admin/cloud_account",
			form:      "tmp_cmd",
			operation: "set_dev_info",
			call:      (*Client).AdminCloudAccountTmpCmdSetDevInfo,
		},
		{
			name:      "AdminCloudAccountTmpCmdUnbindOwner",
			path:      "/admin/cloud_account",
			form:      "tmp_cmd",
			operation: "unbind_owner",
			call:      (*Client).AdminCloudAccountTmpCmdUnbindOwner,
		},
		{
			name:      "AdminCloudAccountUserLoginRead",
			path:      "/admin/cloud_account",
			form:      "user_login",
			operation: "read",
			call:      (*Client).AdminCloudAccountUserLoginRead,
		},
		{
			name:      "AdminCloudAccountUserLoginWrite",
			path:      "/admin/cloud_account",
			form:      "user_login",
			operation: "write",
			call:      (*Client).AdminCloudAccountUserLoginWrite,
		},
	})
}
