package deco

import "testing"

func TestAdminAdministrationMethods(t *testing.T) {
	testAdminMethodCases(t, []adminMethodCase{
		{
			name:      "AdminAdministrationAccountAppget",
			path:      "/admin/administration",
			form:      "account",
			operation: "appget",
			call:      (*Client).AdminAdministrationAccountAppget,
		},
		{
			name:      "AdminAdministrationAccountAppset",
			path:      "/admin/administration",
			form:      "account",
			operation: "appset",
			call:      (*Client).AdminAdministrationAccountAppset,
		},
		{
			name:      "AdminAdministrationAccountMCUCheck",
			path:      "/admin/administration",
			form:      "account",
			operation: "mcu_check",
			call:      (*Client).AdminAdministrationAccountMCUCheck,
		},
		{
			name:      "AdminAdministrationAccountMCURead",
			path:      "/admin/administration",
			form:      "account",
			operation: "mcu_read",
			call:      (*Client).AdminAdministrationAccountMCURead,
		},
		{
			name:      "AdminAdministrationAccountMCUWrite",
			path:      "/admin/administration",
			form:      "account",
			operation: "mcu_write",
			call:      (*Client).AdminAdministrationAccountMCUWrite,
		},
		{
			name:      "AdminAdministrationAccountRead",
			path:      "/admin/administration",
			form:      "account",
			operation: "read",
			call:      (*Client).AdminAdministrationAccountRead,
		},
		{
			name:      "AdminAdministrationAccountSet",
			path:      "/admin/administration",
			form:      "account",
			operation: "set",
			call:      (*Client).AdminAdministrationAccountSet,
		},
		{
			name:      "AdminAdministrationAccountWrite",
			path:      "/admin/administration",
			form:      "account",
			operation: "write",
			call:      (*Client).AdminAdministrationAccountWrite,
		},
		{
			name:      "AdminAdministrationLocalInsert",
			path:      "/admin/administration",
			form:      "local",
			operation: "insert",
			call:      (*Client).AdminAdministrationLocalInsert,
		},
		{
			name:      "AdminAdministrationLocalLoad",
			path:      "/admin/administration",
			form:      "local",
			operation: "load",
			call:      (*Client).AdminAdministrationLocalLoad,
		},
		{
			name:      "AdminAdministrationLocalRemove",
			path:      "/admin/administration",
			form:      "local",
			operation: "remove",
			call:      (*Client).AdminAdministrationLocalRemove,
		},
		{
			name:      "AdminAdministrationLocalUpdate",
			path:      "/admin/administration",
			form:      "local",
			operation: "update",
			call:      (*Client).AdminAdministrationLocalUpdate,
		},
		{
			name:      "AdminAdministrationLoginRead",
			path:      "/admin/administration",
			form:      "login",
			operation: "read",
			call:      (*Client).AdminAdministrationLoginRead,
		},
		{
			name:      "AdminAdministrationLoginWrite",
			path:      "/admin/administration",
			form:      "login",
			operation: "write",
			call:      (*Client).AdminAdministrationLoginWrite,
		},
		{
			name:      "AdminAdministrationModeRead",
			path:      "/admin/administration",
			form:      "mode",
			operation: "read",
			call:      (*Client).AdminAdministrationModeRead,
		},
		{
			name:      "AdminAdministrationModeWrite",
			path:      "/admin/administration",
			form:      "mode",
			operation: "write",
			call:      (*Client).AdminAdministrationModeWrite,
		},
		{
			name:      "AdminAdministrationRecoveryRead",
			path:      "/admin/administration",
			form:      "recovery",
			operation: "read",
			call:      (*Client).AdminAdministrationRecoveryRead,
		},
		{
			name:      "AdminAdministrationRecoveryWrite",
			path:      "/admin/administration",
			form:      "recovery",
			operation: "write",
			call:      (*Client).AdminAdministrationRecoveryWrite,
		},
		{
			name:      "AdminAdministrationRemoteRead",
			path:      "/admin/administration",
			form:      "remote",
			operation: "read",
			call:      (*Client).AdminAdministrationRemoteRead,
		},
		{
			name:      "AdminAdministrationRemoteWrite",
			path:      "/admin/administration",
			form:      "remote",
			operation: "write",
			call:      (*Client).AdminAdministrationRemoteWrite,
		},
		{
			name:      "AdminAdministrationViewLoad",
			path:      "/admin/administration",
			form:      "view",
			operation: "load",
			call:      (*Client).AdminAdministrationViewLoad,
		},
	})
}
