package deco

import "testing"

func TestAdminNetworkMethods(t *testing.T) {
	testAdminMethodCases(t, []adminMethodCase{
		{
			name:      "AdminNetworkDHCPDialRead",
			path:      "/admin/network",
			form:      "dhcp_dial",
			operation: "read",
			call:      (*Client).AdminNetworkDHCPDialRead,
		},
		{
			name:      "AdminNetworkDHCPDialWrite",
			path:      "/admin/network",
			form:      "dhcp_dial",
			operation: "write",
			call:      (*Client).AdminNetworkDHCPDialWrite,
		},
		{
			name:      "AdminNetworkIGMPSettingRead",
			path:      "/admin/network",
			form:      "igmp_setting",
			operation: "read",
			call:      (*Client).AdminNetworkIGMPSettingRead,
		},
		{
			name:      "AdminNetworkIGMPSettingWrite",
			path:      "/admin/network",
			form:      "igmp_setting",
			operation: "write",
			call:      (*Client).AdminNetworkIGMPSettingWrite,
		},
		{
			name:      "AdminNetworkInternetRead",
			path:      "/admin/network",
			form:      "internet",
			operation: "read",
			call:      (*Client).AdminNetworkInternetRead,
		},
		{
			name:      "AdminNetworkInternetWrite",
			path:      "/admin/network",
			form:      "internet",
			operation: "write",
			call:      (*Client).AdminNetworkInternetWrite,
		},
		{
			name:      "AdminNetworkIPv6Read",
			path:      "/admin/network",
			form:      "ipv6",
			operation: "read",
			call:      (*Client).AdminNetworkIPv6Read,
		},
		{
			name:      "AdminNetworkIPv6Write",
			path:      "/admin/network",
			form:      "ipv6",
			operation: "write",
			call:      (*Client).AdminNetworkIPv6Write,
		},
		{
			name:      "AdminNetworkLANIPRead",
			path:      "/admin/network",
			form:      "lan_ip",
			operation: "read",
			call:      (*Client).AdminNetworkLANIPRead,
		},
		{
			name:      "AdminNetworkLANIPWrite",
			path:      "/admin/network",
			form:      "lan_ip",
			operation: "write",
			call:      (*Client).AdminNetworkLANIPWrite,
		},
		{
			name:      "AdminNetworkLANIPv4Read",
			path:      "/admin/network",
			form:      "lan_ipv4",
			operation: "read",
			call:      (*Client).AdminNetworkLANIPv4Read,
		},
		{
			name:      "AdminNetworkLANIPv4Write",
			path:      "/admin/network",
			form:      "lan_ipv4",
			operation: "write",
			call:      (*Client).AdminNetworkLANIPv4Write,
		},
		{
			name:      "AdminNetworkMACCloneRead",
			path:      "/admin/network",
			form:      "mac_clone",
			operation: "read",
			call:      (*Client).AdminNetworkMACCloneRead,
		},
		{
			name:      "AdminNetworkMACCloneWrite",
			path:      "/admin/network",
			form:      "mac_clone",
			operation: "write",
			call:      (*Client).AdminNetworkMACCloneWrite,
		},
		{
			name:      "AdminNetworkPerformanceRead",
			path:      "/admin/network",
			form:      "performance",
			operation: "read",
			call:      (*Client).AdminNetworkPerformanceRead,
		},
		{
			name:      "AdminNetworkVLANRead",
			path:      "/admin/network",
			form:      "vlan",
			operation: "read",
			call:      (*Client).AdminNetworkVLANRead,
		},
		{
			name:      "AdminNetworkVLANWrite",
			path:      "/admin/network",
			form:      "vlan",
			operation: "write",
			call:      (*Client).AdminNetworkVLANWrite,
		},
		{
			name:      "AdminNetworkWANIPv4Connect",
			path:      "/admin/network",
			form:      "wan_ipv4",
			operation: "connect",
			call:      (*Client).AdminNetworkWANIPv4Connect,
		},
		{
			name:      "AdminNetworkWANIPv4Disconnect",
			path:      "/admin/network",
			form:      "wan_ipv4",
			operation: "disconnect",
			call:      (*Client).AdminNetworkWANIPv4Disconnect,
		},
		{
			name:      "AdminNetworkWANIPv4Read",
			path:      "/admin/network",
			form:      "wan_ipv4",
			operation: "read",
			call:      (*Client).AdminNetworkWANIPv4Read,
		},
		{
			name:      "AdminNetworkWANIPv4Write",
			path:      "/admin/network",
			form:      "wan_ipv4",
			operation: "write",
			call:      (*Client).AdminNetworkWANIPv4Write,
		},
		{
			name:      "AdminNetworkWANModeRead",
			path:      "/admin/network",
			form:      "wan_mode",
			operation: "read",
			call:      (*Client).AdminNetworkWANModeRead,
		},
		{
			name:      "AdminNetworkWANModeWrite",
			path:      "/admin/network",
			form:      "wan_mode",
			operation: "write",
			call:      (*Client).AdminNetworkWANModeWrite,
		},
	})
}
